### ISSUE TITLE
SOCIAL MEDIA buttons

### ISSUE THREAD

**Issue by omelki** [FadiZahhar/oldsinks#8]
Make sure that all previewed images have the following share buttons: facebook twitter instagram and pinterest

**Comment by FadiZahhar** [comment]
this is not in our deal. won't do it.

**Comment by omelki** [comment]
As agreed, we'll add them and will force the client to pay for this additional feature

**Comment by FadiZahhar** [comment]
I Added a plugin on the back office called easy social Icons.
You need to set the social icons by uplading the correct png formats , and you can set in case of horizantel display or vertical. In the url just type #social#  I will hook it at the end with a jquery method to force in replacing the #social# symbol to the correct url. This issue is closed.
